project_id = "ykmpvokuleuefafcboip"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
site_url = "https://nova-research-studio.liannevmcclinticztze.chatgpt.site"
additional_redirect_urls = [
  "https://nova-research-studio.liannevmcclinticztze.chatgpt.site/**",
  "https://*.nativelyai.app/**",
  "https://**.webcontainer-api.io/**",
  "https://**.daytonaproxy01.net/**",
  "http://localhost:5173/**",
  "http://127.0.0.1:5173/**",
  "http://127.0.0.1:5174/**",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.research-manager]
verify_jwt = true

[functions.search-agent]
verify_jwt = true

[functions.paper-reader]
verify_jwt = true

[functions.reasoning-gap]
verify_jwt = true

[functions.scientist-hypothesis]
verify_jwt = true

[functions.report-writer]
verify_jwt = true

[functions.invite-member]
verify_jwt = true

[functions.writing-assistant]
verify_jwt = true

[functions.paper-validator]
verify_jwt = true

[functions.professional-agent]
verify_jwt = true

[functions.open-research]
verify_jwt = true

[functions.external-similarity]
verify_jwt = true
